---
- name: Verify st2chatops using bin/hubot
  # when editing, make sure it works for at least 2 adapters: 'shell' and 'slack'
  shell: >
    set -o pipefail &&
    export a=/tmp/.hubot.{{ 10000 | random }}.attempts &&
    export n=$(cat $a 2>/dev/null || echo 0) &&
    timeout $(( 9 + 5 ** n )) bash -c '(sleep $(( 4 + 5 ** n )); echo exit ) | bin/hubot' &&
    echo $((n+1)) > $a
  # $a,$n = homegrown exponential backoff (increasing sleep lets the slack client lib retry automatically)
  args:
    chdir: /opt/stackstorm/chatops/
    executable: /bin/bash
  environment:
    HUBOT_LOG_LEVEL: debug
  register: hubot_output
  failed_when: no
  changed_when: no
  # any EADDRINUSE error in stdout is normal (an artifact of the js express http framework)
  # On Travis, with failures when running many builds in parallel, the real error message is:
  # "Rate limited, will retry # seconds". This comes from @slack/client (used by hubot-slack).
  # On success (with Slack), the log says: 'SlackBot#authenticated() Found self in RTM start data'
  until: "'Rate limited, will retry' not in hubot_output.stdout_lines | last"
  retries: 3
  # random delay so that retries accross parallel runs don't perfectly align
  delay: "{{ 15 + (7 | random) }}"

# Additional task to provide better error message
- name: Fail if st2chatops couldn't load st2 commands
  fail:
    msg: |
      Please check you 'st2chatops' configuration!
      Expected message "{{ item }}" not found in 'hubot' output.
      Full chatops log: {{ hubot_output.stdout }}
  when: item not in hubot_output.stdout
  loop:
    - "DEBUG Loading adapter {{ st2chatops_hubot_adapter }}"
    - "DEBUG Loading scripts from /opt/stackstorm/chatops/src/scripts"
    - "DEBUG Added command: pack get"
    - "commands are loaded"
